version: '3'

volumes:
  mongodb_api:

services:
  api_db:
    ports:
      - 3000:27017

  api:
    command: yarn dev
    ports:
      - 3001:3001
    environment:
      NODE_ENV: development
    volumes:
      - ./api/src:/usr/src/app/src

  frontend:
    command: yarn dev
    environment:
      NODE_ENV: development
    ports:
      - 3002:3002
    volumes:
      - ./frontend/pages:/usr/src/app/pages
      - ./frontend/public:/usr/src/app/public

  nginx:
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/nginx.conf
