version: "3.4"

x-common-app:
  environment: &next-env
    HOST: http://mydocker.local
    MAIN_ORIGIN: http://next-main:3000
    AUTH_ORIGIN: http://next-auth:3001/auth
    DB_ORIGIN: http://mongo-db:3002
    NEXT_TELEMETRY_DISABLED: 1
    NODE_ENV: production
    MONGO_URL: mongodb://mongo-db:27017/default

volumes:
  mongo-db:

services:
  nginx:
    container_name: mydocker-nginx
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - next-main
      - next-auth

  next-main:
    container_name: mydocker-next-main
    build: ./next-main
    command: yarn start
    restart: unless-stopped
    depends_on:
      - mongo-db
    environment:
      <<: *next-env
      PORT: 3000

  next-auth:
    container_name: mydocker-next-auth
    build: ./next-auth
    command: yarn start
    restart: unless-stopped
    depends_on:
      - mongo-db
    environment:
      <<: *next-env
      PORT: 3001

  mongo-db:
    container_name: mydocker-mongo-db
    image: mongo:latest
#    command:
#      - --logpath
#      - /var/log/mongodb/mongod.log
    restart: unless-stopped
    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: default
    volumes:
      - mongo-db:/data/db
